### ISSUE TITLE
peer to peer code review #1

### ISSUE THREAD

**Issue by TashfeenRao** [Rhelli/Basic-HTML-Page-Structure#2]
it is good

**Comment by tcc7130** [comment]
Good things:

- Clean code

- Font awesome

- Descriptive commits

Bad things (not that bad):

- Readme file (needs a little more description)

- Code comments (there aren't supposed to be any comments)

**Comment by Fig77** [comment]
Code looks pretty clean and tidy. 
Overall I noticed that semantic html is not being used. Beside that I don't have other observation.
